jobs:
- name: test
  plan:
  - aggregate:
    - get: stemcell
    - get: bosh-deployment
    - get: docker-release
    - get: xenial-ops-file
  - put: cloud-config
    params:
      manifest: bosh-deployment/((bosh_cpi))/cloud-config.yml
      releases: []
  - put: deploy
    params:
      manifest: docker-release/manifests/swarm/docker-swarm.yml
      stemcells: [ stemcell/stemcell.tgz ]
      ops_files: [ xenial-ops-file/xenial-ops-file.yml ]

resources:
- name: xenial-ops-file
  type: file
  source:
    filename: xenial-ops-file.yml
    content:
    - type: replace
      path: /stemcells/alias=default/os
      value: ubuntu-xenial

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
    branch: master

- name: docker-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/docker-boshrelease.git
    branch: master

- name: stemcell
  type: bosh-io-stemcell
  source:
    name: ((bosh_stemcell))

- name: deploy
  type: bosh-deployment
  source:
    <<: *deployment
    <<: *bosh_env

- name: cloud-config
  type: bosh-config
  source:
    type: cloud-config
    <<: *bosh_env

params:
  bosh_env: &bosh_env
    target: ((bosh_environment))
    client: ((bosh_client))
    client_id: ((bosh_client))
    client_secret: ((bosh_client_secret))
    ca_cert: ((bosh_ca_cert))
  deployment: &deployment
    deployment: docker-swarm

resource_types:
- name: bosh-config
  type: docker-image
  source:
    repository: rkoster/bosh-config-resource
    tag: latest

- name: file
  type: docker-image
  source:
    repository: aequitas/concourse-file-resource
    tag: latest

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: latest
