---
meta:
  name: bucc
  target: ci2
  url:     https://ci2.starkandwayne.com
  lite:
    target: 10.10.1.5
  vcenter:
    username: ((vcenter_username))
    password: ((vcenter_password))
  github:
    owner: starkandwayne
    repo:  bucc
    private_key:  ((github_private_key))
    access_token: ((github_acces_token))
  aws:
    access_key_id: ((aws_access_key))
    secret_access_key: ((aws_secret_key))
  slack:
    webhook: ((slack_webhook))
    channel: "#bucc"
